# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildApp
    jobs:
      - job: BuildAndPush
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker_repo'
            repository: 'elnabawy/azure_web_image'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'