apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      containers:
        - name: simple-web
          image: elnabawy/simple-web-app
          ports:
            - name: httpport
              containerPort: 80
