apiVersion: v1  
kind: Service
metadata:
  name: simple-web-service
  namespace: simple-web
spec:
  selector: 
    app: simple-web-server
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 80
